### ISSUE TITLE
Cannot connect to server running on /path

### ISSUE THREAD

**Issue by heilmela** [colyseus/colyseus.js#125]
We are running a server instance behind a reverse proxy with a path prefix e.g.  
`wss://tld.dev/colyseus` https://github.com/colyseus/colyseus.js/blob/bde0b32d0e2c3383e5d5358b07c4b12010434cee/src/Client.ts#L40
The default settings and parsing of the url introduced in 0.14.3 basically throws away any url paths, we are pretty much stuck on 0.14.2 where this worked.

**Comment by endel** [comment]
Oh no! Thanks for reporting
