### ISSUE TITLE
On joinOrCreate, room.state is empty

### ISSUE THREAD

**Issue by perspectivezoom** [colyseus/colyseus.js#130]
Is this intended? Or am I missing some trigger or doing something out of order to cause `room.state` to not be populated?

I've been trying to reproduce https://github.com/ourcade/tic-tac-toe-multiplayer-starter, and I've also looked at https://github.com/endel/colyseus-tic-tac-toe, and both of them seem to assume that `room.state` is populated from initial join.

If it is intended to be initially empty, how do I trigger the initial population of the `room.state`?

|Description|Code|`console.log`|
|---|---|---|
|`state` seems to be populated correctly at `onJoin` time on the server|<img width="605" alt="Screen Shot 2023-09-04 at 6 04 38 PM" src="https://github.com/colyseus/colyseus.js/assets/1837622/b8229b32-c900-4330-939b-7e53429ed4aa">|<img width="359" alt="Screen Shot 2023-09-04 at 6 04 57 PM" src="https://github.com/colyseus/colyseus.js/assets/1837622/e4ee0557-b1ff-4491-a438-17ac72432e99">|
|On the client side, `client.joinOrCreate` shows empty values for `room.state`|<img width="595" alt="Screen Shot 2023-09-04 at 6 02 20 PM" src="https://github.com/colyseus/colyseus.js/assets/1837622/98ee356f-c24b-4b88-8f84-88731163467b">|<img width="1512" alt="Screen Shot 2023-09-04 at 6 01 49 PM" src="https://github.com/colyseus/colyseus.js/assets/1837622/cf7bffcb-b5ef-46e1-b8cf-8ac03806ac08">|
|Websocket event. Is there a way I can decode the payload to see if the server is sending the right thing or not?|N/A|<img width="887" alt="Screen Shot 2023-09-04 at 6 03 20 PM" src="https://github.com/colyseus/colyseus.js/assets/1837622/f5dfb465-59d3-440b-82f4-e79339f734cb">|
|GameState Schema for reference|<img width="653" alt="Screen Shot 2023-09-04 at 6 04 17 PM" src="https://github.com/colyseus/colyseus.js/assets/1837622/5518bd40-3f6a-4e3e-93fa-1fda9617ef65">|N/A|

**Comment by endel** [comment]
Hi @perspectivezoom, the `room.state` on the client-side is not **immediately** populated after connecting, but after a few milliseconds, it does get synchronized. 

Both your `.listen("activePlayer")` and `.room.onStateChange(()=>{})` should be triggering after joining the room. If they're not triggering you may be hitting a known server config issue that causes the state not to sync, [documented here](https://github.com/colyseus/colyseus/issues/510#issuecomment-1507828422). If your project was created via `npm create colyseus-app@latest` that config is already set.

> "Websocket event. Is there a way I can decode the payload to see if the server is sending the right thing or not?"

You can use the playground tool to inspect every message https://docs.colyseus.io/tools/playground/

---

Let me know if that helps, otherwise please share your project so I can take a look. Cheers!

**Comment by perspectivezoom** [comment]
> If they're not triggering you may be hitting a known server config issue that causes the state not to sync, https://github.com/colyseus/colyseus/issues/510#issuecomment-1507828422.

This was totally it. Setting `"useDefineForClassFields": false`, everything magically works.

> the `room.state` on the client-side is not **immediately** populated after connecting, but after a few milliseconds, it does get synchronized

According to `console.log`, I don't ever see the blank state. As far as my application code is concerned, it works immediately.

<img width="1510" alt="Screen Shot 2023-09-04 at 7 22 54 PM" src="https://github.com/colyseus/colyseus.js/assets/1837622/c1dd20c3-965d-488b-a96e-26813d69b52c">

> You can use the playground tool to inspect every message https://docs.colyseus.io/tools/playground/

It doesn't seem to work for me. I can see the room, but no active connections. But as no longer have an immediate use for inspecting websocket events and this is a problem only tangentially related, I'm closing this issue out. Thanks so much @endel for your help. I've spent pretty much the entire day trying to figure this out.

|||
|---|---|
|<img width="528" alt="Screen Shot 2023-09-04 at 7 30 55 PM" src="https://github.com/colyseus/colyseus.js/assets/1837622/3df60fc3-4d08-4cb5-9737-f4672c5df85b">|<video src="https://github.com/colyseus/colyseus.js/assets/1837622/90f3d679-8f75-41c5-bf5e-5565671f32a4" />|
