### ISSUE TITLE
Colysesus.js with Angular

### ISSUE THREAD

**Issue by riccardorinaldi7** [colyseus/colyseus.js#137]
Hi, is there any chance that colyseus.js library can work inside an Angular application? Thank you.

**Comment by endel** [comment]
Hey @riccardorinaldi7, what's the issue you're currently experiencing? 

The SDK should be working fine on Angular. If you're talking about state sync issues you might be experiencing this: https://github.com/colyseus/colyseus/issues/510#issuecomment-1507828422
