### ISSUE TITLE
Cocos Creator Client v0.15.25 released folder wasnt build

### ISSUE THREAD

**Issue by nolandpham** [colyseus/colyseus.js#145]
Please check https://github.com/colyseus/colyseus.js/archive/refs/tags/0.15.25.zip
It wasnt builded to colyseus-cocos-creator.js and colyseus.d.ts files.

Evidence:
![Screenshot 2024-07-15 at 17 12 57](https://github.com/user-attachments/assets/64165fc3-76a4-4942-a2b2-60f9bd32aefe)

**Comment by endel** [comment]
Hi @nolandpham, thanks for the heads-up, just uploaded it here: 
https://github.com/colyseus/colyseus.js/releases/download/0.15.25/colyseus-sdk.zip
