### ISSUE TITLE
Allow to use it on Node.js environment without manipulating global scope.

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus.js#25]
As [pointed out](https://discuss.colyseus.io/topic/62/is-there-a-way-to-use-colyseus-js-on-a-node-environment-in-a-non-hack-way) by @holywyvern - currently it's required to populate the `global` scope in order to get the JavaScript client running on Node.js environment.

It would be better to provide a way to support Node.js without messing up with the `global` scope.

**Something like:**

```typescript
import { Client } from "colyseus.js";

const Storage = require("dom-storage");
const WebSocket = require("uws");

const client = new Client("endpoint", { 
  storage:  new Storage(null, { strict: true }),
  ws: WebSocket
});
```

**Comment by endel** [comment]
The `@gamestdio/websocket` package may need to be updated to support Node.js environment in a similar way.

**Comment by cayasso** [comment]
Would this be the same case for `React-Native` and `window.localStorage`?

**Comment by endel** [comment]
As of [0.9.16](https://github.com/colyseus/colyseus.js/releases/tag/0.9.16), this client now works on Node.js environment out of the box, you just need to include `ws` as a dependency in your project. 🙌

**Comment by cayasso** [comment]
Thank you @endel! 
Does this fix apply for `React-Native`?

**Comment by endel** [comment]
@cayasso you're welcome :) 

Unfortunately, for `react-native` it is still necessary to do the "hacks" described in the README: https://github.com/colyseus/colyseus.js#react-native-compatibility
