### ISSUE TITLE
Typescript+namespaces not incompatible with gamestdio lib(clock,signals,..).

### ISSUE THREAD

**Issue by AlexanderKolarov** [colyseus/colyseus.js#28]
Typescript+namespaces cannot be used with current build of gamestdui lib(Clock,Signals, ..).

The client is divided in 2 parts : colyseus.js + gamestdio_lib(clock,signal,..).

So colyseus.js works under namespace window.Colyseus. Example: `window.Colyseus.Client;`
But gamestdio_lib works with module loader. Example: `require('Signals');`

To be used the both parts of the client through Typescript+namespaces, is needed gamestdio_lib under 
something like `window.Signals` or` window.gamestdio_lib.Signals`.

I know one **_solution_** : **take the gamestdio_lib classes, change them into namespaces and build them 
es5.** 

Small client apps are better to be built without module loaders according Typescript documentation.

**Comment by AlexanderKolarov** [comment]
This is the source of Colyseus.d.ts : [https://github.com/AlexanderKolarov/colyseujs-typescript-namespaces](url). Just empty functions.

I looked the lib classes. They will be changed by ease from modules to namespaces. 

Soon I will convert all classes(.ts) in colyseus-client and lib to namespaces. 
With all classes I mean not just empty functions just to generate d.ts, but the whole logic.

Where should I register my change ?

**Comment by TakesTheBiscuit** [comment]
https://github.com/AlexanderKolarov/colyseujs-typescript-namespaces

**Comment by endel** [comment]
Keeping the static `.d.ts` file up-to-date with the latest version of the client is still an open issue to be solved. If anyone knows an automated way to have a single `.d.ts` file for the entire lib based on the typescript sources, it would be really cool!
