### ISSUE TITLE
Can a Entity have property of type array or object

### ISSUE THREAD

**Issue by TreantBG** [colyseus/colyseus.js#44]
Hello,

I'm trying to make multipalyer snake game.
So every player have a body of dots with x,y coordinates.
It seems i cannot hold it in the entity object as array or object of objects
like this:
```
public snake = {};
snake['head'] = {x:0,y:0}
```

or like this

```
public snake = [];
snake.push({x:0,y:0})
```

I get only the ADD state operation but after changing the values inside the snake varriable i don't get any updates

My listener is watching for any changes but nothing comes ....
`this.room.listen("players/:id/:attribute" `

**Comment by oyed** [comment]
If it is an object you'll have to listen to keys, e.g.
```
this.room.listen('players/:id/:attribute/:key'
```

**Comment by TreantBG** [comment]
I don't get updates only ADD operation is active
With this method i get

```
operation: "add"
path: {id: "NjyPJhfbJ", attribute: "snake", key: "head"}
rawPath: (4) ["players", "NjyPJhfbJ", "snake", "head"]
value: {x: 167, y: 135}
```

and then nothing.
i print on the server the value of snake and its deferentially different and changed

i read about the MessagePack limitations is this the case?

**Comment by endel** [comment]
hey @TreantBG, looks like you're only listening to the variable itself, you need to listen for its properties to catch changes as well:

```typescript
this.room.listen("players/:id/snake", (change) => {
// listens for "add" or "remove" of snakes
});

this.room.listen("players/:id/snake/head/:attribute", (change) => {
// here you should be able to get any attribute change from the "head" object
// change.path.attribute => "x", "y", etc
});
```

It's not recommended to sync every single "block" of the snake btw. You'd probably save a lot of traffic by having just the snake position and its length, and positioning the body blocks of the snake in the client-side, based on its length and moving path

cheers!

**Comment by TreantBG** [comment]
Hi @endel 
Thank you very much that works! 
We need more documentation and examples about your project. I didn't know you can use this style of listening and i read all the sections about state management.
And yes i wont send all the parts but the initial snake data like head direction and so on.

I will try to publish some documentation of my findings and share my experience with your project.

Thanks again.

**Comment by IanMayo** [comment]
@TreantBG - you'd be surprised how easy it is to contribute to the docs. Find the section that relates to your new content, then click on the `Edit` button:
![image](https://user-images.githubusercontent.com/1108513/52261992-08d0b300-2923-11e9-87cb-c07f7ee6c869.png)

You will end up with a Pull Request that the maintainer(s) just merge in.  I only made a minor correction, but it was easy :-)
https://github.com/colyseus/docs/pull/11

**Comment by endel** [comment]
that's right @IanMayo ❤️ once the pull-request has been made, [Netlify](https://www.netlify.com/) provides a preview link inside the pull-request, it's super handy
