### ISSUE TITLE
Getting metadata from a connected room

### ISSUE THREAD

**Issue by gmfc** [colyseus/colyseus.js#45]
Hi,

I was wondering if its possible to access the metadata of a connected room.

the metadata is available using the [client.getAvailableRooms()](https://docs.colyseus.io/client-overview/#getavailablerooms-roomname-string) method

```Typescript
client.getAvailableRooms('map', (rooms, err) => {
  rooms.forEach((room) => {
   console.log(room.metadata) // Here it is
  })
})
```

but once you connect to a room we loose access:

```Typescript
client = new Client(ENDPOINT)
room = this.client.join('map')

room.metadata // Nothing here...

```
I saw that [RoomAvailable](https://github.com/colyseus/colyseus.js/blob/master/src/Room.ts#L11) has the metadata attribute, but [Room](https://github.com/colyseus/colyseus.js/blob/master/src/Room.ts#L18) itself doesn't.

Is it possible to pass this attribute to the connected Room instance?

Thanks!

**Comment by endel** [comment]
Hey @gmfc, I'm curious what's your use case for this. The `metadata` property was meant to be used only for room listing / matchmaking. Can't you populate the same data you're interested in the `state` as well?

**Comment by gmfc** [comment]
I needed to retrieve data such as what assets to use and witch listeners to register for the connected room.
This need to be done before registering some listeners.
Example:
```Typescript
import { Client, DataChange, Room } from 'colyseus.js'

export class TestApp {
  room: Room
  client: Client
  ENDPOINT = 'ws://localhost:1234/'
  constructor () {
    this.client = new Client(this.ENDPOINT)
    this.room = this.client.join('dynamic_room')
    this.room.listen('listenerData', ({ operation, value }: DataChange) => {
      if (operation === 'add') {
        switch (value) {
          case 'battleMap':
            this.setAssets('battleMap')
            // Listeners wont catch all 'add' events
            this.registerListenersFor('battleMap')
            break
          case 'battleRoyaleMap':
            this.setAssets('battleRoyaleMap')
            // Listeners wont catch all 'add' events
            this.registerListenersFor('battleRoyaleMap')
            break
        }
      }
    })
  }
}

```
Using metadata:

```Typescript
import { Client, DataChange, Room } from 'colyseus.js'

export class TestApp {
  room: Room
  client: Client
  ENDPOINT = 'ws://localhost:1234/'
  constructor () {
    this.client = new Client(this.ENDPOINT)
    this.room = this.client.join('dynamic_room')
    this.setAssets(this.room.metadata.assets)
    // Listeners will catch all events
    this.registerListenersFor(this.room.metadata.mapType)
  }
}
```

What I observed was that using something similar to the first example, objects already added to the state won't trigger the 'add' event for the connected room (NPCs created when the room first initialize)

Example:
```Typescript
import { Client, DataChange, Room } from 'colyseus.js'

export class TestApp {
  room: Room
  client: Client
  elements: any[]
  ENDPOINT = 'ws://localhost:1234/'
  constructor () {

    this.client = new Client(this.ENDPOINT)
    this.room = this.client.join('dynamic_room')

    this.room.listen('something', ({ operation }: DataChange) => {
      if (operation === 'add') {
        // Wont catch elements already in the state
        this.room.listen('somethingElse', ({ operation, value }: DataChange) => {
          if (operation === 'add') this.elements[value.id] = value
        })
      }
    })

  }
}
```

I may be missing something here 🤔 ...

**Comment by endel** [comment]
@gmfc Thanks! The `listen` method accepts a third argument which means "immediate" - that will trigger the changes immediately:

```
this.room.listen('something', (change) => {}, true);
```

I just noticed this hasn't been documented 🤔

**Comment by endel** [comment]
The metadata won't be available to the client-side tho, I'd recommend using the solution you're currently using, or using `this.send()` from the room handler to notify the user about the data.

**Comment by gmfc** [comment]
The immediate thing does it!
Thanks again!
