### ISSUE TITLE
Support non-browser client

### ISSUE THREAD

**Issue by pjc0247** [colyseus/colyseus.js#46]
I know it's not common write a game client with NodeJS. but some people wants to make a straightforward client with Javascript for testing purpose.

Current version cannot be executed on NodeJS with following error:
```
ws does not work in the browser. Browser clients must use the native WebSocket object
```

**Comment by endel** [comment]
Hi @pjc0247, we recently added support for Node.js: https://github.com/colyseus/colyseus.js/issues/25

How your environment looks like? I've just tested adding `colyseus.js` and `ws` as dependencies on `package.json`, and it works fine. The loadtest tool also uses the JavaScript client (https://github.com/colyseus/colyseus-loadtest)

Cheers!

**Comment by pjc0247** [comment]
@endel I didn't notice that there's already support for NodeJS env.

Thanks!
