### ISSUE TITLE
0.11.0

### ISSUE THREAD

**Issue by lavren1974** [colyseus/colyseus.js#54]
room.onMessage not working, function undefined

**Comment by endel** [comment]
Hey @lavren1974 are you sure you're using `colyseus.js@^0.11.0` ?

**Comment by lavren1974** [comment]
"dependencies": {
    "bootstrap": "^4.3.1",
    "colyseus.js": "^0.11.0",
    "firebase": "^6.4.0",
    "jquery": "^3.4.1",
    "popper.js": "^1.15.0",
    "react": "^16.9.0",
    "react-bootstrap": "^1.0.0-beta.11",
    "react-dom": "^16.9.0",
    "react-router-dom": "^5.0.1",
    "react-scripts": "3.1.1",
    "recompose": "^0.30.0"
	
....
	
	class Game extends React.Component {

    constructor(props) {
        super(props);

        this.colyseus = new Colyseus.Client('ws://localhost:2567')
        this.GameBotRoom = this.colyseus.joinOrCreate("gamebot")

        this.state = {

            squares: [],
			
.....

this.GameBotRoom.addListeners.onMessage((data) => {
                if (data.command === "join") {
                    console.log(data.message)
                } else if (data.command === "game_start") {
                    console.log("game_start")

                    this.setState({
                        squares: data.array_squares,
                        squares_valid: data.array_squares_valid
                    })
                }
            });
...

On version 0.10.8 it works!

**Comment by endel** [comment]
Hey @lavren1974, `joinOrCreate()` returns a `Promise` now, not a `Room`. Please check the migration guide: https://docs.colyseus.io/migrating/0.11/#new-match-making-methods-available-in-the-client-side

**Comment by lavren1974** [comment]
Sorry
this.GameBotRoom.onMessage.add ((data) => {

It was! In version 0.10.8 - it works, in version 0.11.0 the onMessage function is not defined

**Comment by lavren1974** [comment]
And how now to receive messages from the server?

**Comment by endel** [comment]
Try this:

```typescript
this.colyseus.joinOrCreate("gamebot").then(room => {
  room.onMessage((data) => {
    console.log("Received", data)
  });
})
```

**Comment by lavren1974** [comment]
Thank!
It works now!!!
I did not carefully read the transition to 0.11.0

this.GameBotRoom = this.colyseus.joinOrCreate ("gamebot")

....

this.GameBotRoom.then (room => {
             room.onMessage ((data) => {
                 if (data.command === "join") {
                     console.log (data.message)
                 } else if (data.command === "game_start") {
                     console.log ("game_start")

                     this.setState ({
                         squares: data.array_squares,
                         squares_valid: data.array_squares_valid
                     })
                 }
             });
         })
