### ISSUE TITLE
invalid byte error show up constantly

### ISSUE THREAD

**Issue by RonnyHou** [colyseus/colyseus.js#60]
using version 0.11.5
I get errors of invalid byte like below:
    Invalid byte 8c;at socketTask.onMessage callback function
    Error: Invalid byte 8c
    at e.t.decode
    at t.setState
    at t.setState
    at t.onMessageCallback

**Comment by endel** [comment]
Can you provide some more context on this @RonnyHou? Which serializer are you using? Which kind of data are you transferring? When exactly does this happen?

**Comment by RonnyHou** [comment]
The error does not show up anymore recently. I consider it a coding mistake of myself. Thanks @endel .
