### ISSUE TITLE
Public distribution file: emit header comment with version number

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus.js#61]
Right now it's not possible to know which version of `colyseus.js` is being used if the file is grabbed manually from `dist/` folder.

We should have a header stating its version number:

```typescript
/* v0.11.7 */
...
```

**Comment by seiyria** [comment]
Could you also do a global.colyseus.version? That might be easier since you can import your package.json as part of the build process.

**Comment by endel** [comment]
Sounds better! 😅  Thanks @seiyria

**Comment by endel** [comment]
I'm going to close this for now as the header has been placed on the `dist/colyseus.js` file. 

To ensure a `Client.VERSION` is also available we'd need to somehow modify the `lib/*` files generated by TypeScript, which are not post-processed by webpack so far, but as the version is already listed on `package.json` and `package-lock.json` I believe that's not much of a problem.
