### ISSUE TITLE
Room listeners are not triggered in Javascript client

### ISSUE THREAD

**Issue by ArdaNakisci** [colyseus/colyseus.js#62]
Hi @endel,

I have just upgraded to version 0.12.0 without changing any code. I was previously using the latest version available. 
The server receives messages with no problems but in the client-side listeners are not triggered at all.
When I downgrade to the 0.11.x version everything works as expected.

**Comment by endel** [comment]
Hi @ArdaNakisci, which listeners are not being triggered? Can you provide a small code example? Thanks!

**Comment by ArdaNakisci** [comment]
`onStateChanged` and `onMessage` doesn't work for me. 

These are the codes that I'm using
`this.props.room.onStateChange(state => {
            // We update the UI after state changes
            this.chooseStateAction(state.soloModeState)
        })`
`this.props.room.onMessage(message => {
            this.chooseMessageAction(message)
        })`

Also like I said when I downgrade to 0.11.x this works without any problem.

**Comment by minviable** [comment]
So you updated colyseus both in server and client application?

You say you upgraded - but does that mean both pieces for you? Would be good to know which client you are using? (js / construct / haxe / defold.. unity..)

**Comment by endel** [comment]
I've just tried v0.12 on both client and server using React Native on Android, and I'm receiving both `onStateChange` and `onMessage` callbacks 👀 

Are you sure the `colyseus.js` package have been updated? Maybe you need to clear expo's cache!

```
expo --clean
```

**Comment by ArdaNakisci** [comment]
Alright, I will give it another try when I have the chance. I'll let you know!

**Comment by arvindr21** [comment]
Upgrading both server and client to `12.0` worked. Thanks, @endel @ArdaNakisci @minviable

**Comment by ArdaNakisci** [comment]
Sorry for the really late reply but everything works fine! Thanks!
