### ISSUE TITLE
Incompatibility with SSR/static site builders [gatsby]

### ISSUE THREAD

**Issue by MarcusCemes** [colyseus/colyseus.js#64]
## Context

`colyseus.js` does not work with Gatsby. Upon trying to build, the build will fail.

The most curious thing is, **this happens even by just importing the `Client` class**, without actually instantiating or executing any `colyseus.js` code...

```ts
import { Client } from "colyseus.js"
...
const client = Client;  // inside React render function, executes at runtime
```

These two lines will cause the build to fail. The second line is there only to prevent the import from being left out by tree-shaking, it merely assigns a reference to the class.

```
ERROR #98123  WEBPACK
Generating SSR bundle failed
Can't import the named export 'globalAgent' from non EcmaScript module (only default export is available)
File: node_modules/httpie/dist/index.mjs

ERROR #98123  WEBPACK
Generating SSR bundle failed
Can't import the named export 'parse' from non EcmaScript module (only default export is available)
File: node_modules/httpie/dist/index.mjs

ERROR #98123  WEBPACK
Generating SSR bundle failed
Can't import the named export 'request' from non EcmaScript module (only default export is available)
File: node_modules/httpie/dist/index.mjs

ERROR #98123  WEBPACK
Generating SSR bundle failed
Can't import the named export 'resolve' from non EcmaScript module (only default export is available)
File: node_modules/httpie/dist/index.mjs

not finished Building static HTML for pages - 1.532s
```

## Reproduction

This is a minimal Gatsby non-typescript starter, with `colyseus.js` as a dependency, and a single import and reference to the `Client` class on the main page (index.js).

[![Edit great-wood-3bnw4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-wood-3bnw4?fontsize=14&hidenavigation=1&theme=dark)

## Workaround

It's possible to patch the WebPack config to resolve `colyseus.js` as null during SSR, as described in [Gatsby's docs](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules). 

```js
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /colyseus\.js/, // crashes build on import
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
```

This fixes the error caused by importing during SSR, but will still include the library in the final browser bundle, benefitting from intelligent pre-fetching, static builds, etc. The only catch is that any colyseus-related code (such as accessing the `Client` class) must be used in `useEffect` hooks which defer to browser execution.

I know that Colyseus is not designed for SSR etc... But I moved to Gatsby to overcome some brick wall limitations of the Create-React-App, after getting frustrated by long custom WebPack configs, and parcel failing miserably.

**Comment by oyed** [comment]
We could possibly add some documentation about this, but beyond that, I'm not sure there's anything we should do - I encountered the same issue recently (Nuxt.js) and did a similar thing (Lazy-loading Game code until they hit /play so it's client-side only)

**Comment by lukeed** [comment]
This error message shows that the Node.js version of `httpie` is being loaded. The ESM format is being understood just fine, but it can't find the exports from `http` or `path` because those modules don't exist.

The quick fix is to configure Gatsby so that the "browser" entry is resolved with priority, or to add an alias directly to the httpie file if you don't want "browser" entries globally for some reason.

Colyseus can also directly import the browser version of httpie if it doesn't intend on being universal.

**Comment by Elyx0** [comment]
Could be part of some FAQ if that solves it @lukeed

**Comment by lukeed** [comment]
Hey, I just sent out a new `httpie@next` build that should make it easier to enforce which files get picked up.

It includes an `exports` map for native ESM support – and it also places each "mode" into a separate directory for easy access. Earlier I said:

> Colyseus can also directly import the browser version of httpie if it doesn't intend on being universal.

So if that _is_ the case, you can now do this to 100% bypass anything Gatsby will cause (or fail to do):

```js
// use the XHR version directly
import * as httpie from 'httpie/xhr';

// use the fetch() version directly
import * as httpie from 'httpie/fetch'; 

// use the node version directly
import * as httpie from 'httpie/node';

// should still resolve correctly per-environment
// but only with bundlers/builds that respect the different package.json keys
import * as httpie from 'httpie';
```

It's been a while, but hope that still helps~!

**Comment by endel** [comment]
I believe this has been fixed on the latest version! Feel free to re-open if this is still breaking for you!
