### ISSUE TITLE
Feature proposal: a way to generate id's similar to sessionId's

### ISSUE THREAD

**Issue by virtumonde** [colyseus/colyseus.js#65]
Pretty much the title. Create a way to generate id's similar to sessionId's

**Comment by seiyria** [comment]
Any particular reason for this? [uuid](https://www.npmjs.com/package/uuid) works generally for most unique purposes.

**Comment by endel** [comment]
It's not documented but there is a `generateId()` which is the same function used for sessionId's: https://github.com/colyseus/colyseus/blob/229a5a49b6ca72f701b6c53e173ceab41d3a4127/src/index.ts#L28

```typescript
import { generateId } from "colyseus" 
```

**Comment by virtumonde** [comment]
That was fast! Thank you, @endel.

**Comment by virtumonde** [comment]
@seiyria No particular reason, I want to use the same id generator as in Colyseus just for the sake of consistency.
