### ISSUE TITLE
Cannot use colyseus.js 0.13.1 in Cocos Creator

### ISSUE THREAD

**Issue by Sengvila** [colyseus/colyseus.js#70]
I copied colyseus.js from dist folder. But after I imported this module in script, I got an error in Cocos Creator and cannot load the game.

Simulator: E/jswrapper (272): ERROR: Uncaught ReferenceError: self is not defined, location: dst/assets/Script/colyseus.js:0:0

**Comment by ramontavarez** [comment]
same issue here but only when i try to run on Simulator.
running in browser is working well

**Comment by ramontavarez** [comment]
![image](https://user-images.githubusercontent.com/10215019/93071959-2b769200-f657-11ea-90d7-c4ac50d9e6e2.png)

if you add this line on the beggining of colyseus.js the error will stop
but i don't know if this will stop colyseus from working

**Comment by endel** [comment]
Hi guys, version `0.14.4` shouldn't require any workarounds, and there are nice instructions on how to get it going on Cocos Creator 3 here now: https://docs.colyseus.io/getting-started/javascript-client/#cocos-creator-30

Please let me know if you run into any issues! Cheers!
