### ISSUE TITLE
Error running jest tests with v0.13.1

### ISSUE THREAD

**Issue by jjhamshaw** [colyseus/colyseus.js#71]
(I've created a repo with the issue, so it can be reproduced: https://github.com/jjhamshaw/colyseus-example)

## Steps to reproduce

- create a fresh create-react-app
- install colyseus@0.13.1
- create a new instance of a `Room` in a test
- run `yarn test`

I'm getting this error with from nanoEvents (there's a test in the example repo to show this [here](https://github.com/jjhamshaw/colyseus-example/blob/master/src/Example.test.tsx)):

```
TypeError: nanoevents_1.createNanoEvents is not a function

      2 |
      3 | test("this should work", () => {
    > 4 |   const room = new Room("name");
        |                ^
      5 |   expect(room).toBeDefined();
      6 | });
      7 |
```

**note: colyseus@0.13.0 works as expected**

**Comment by endel** [comment]
Thanks for reporting @jjhamshaw, I found this other issue that's related to what you're describing here: https://github.com/ai/nanoevents/issues/45

Not really sure what we can do to fix this. It seems to me that the entire Node.js / NPM ecosystem is moving towards cjs / module pattern and the existing tooling is not keeping up with that. Here's a similar issue with a different dependency and environment https://github.com/colyseus/colyseus.js/issues/64

I think `colyseus.js` should provide alternative entry points on its `package.json` for better integration with modern browser/node/cjs/whatever environments.

**Comment by jjhamshaw** [comment]
@endel thanks for the quick reply (unlike mine...).

Got it, the issue is clearly not with colyseus but with tooling i.e. jest. I don't actually need to create an instance of a `Room` now, instead I'm just mocking it - so kind of a workaround!
