### ISSUE TITLE
Cannot create client with React Native

### ISSUE THREAD

**Issue by rhetoricalraj** [colyseus/colyseus.js#72]
Error in Chrome: `TypeError: Cannot assign to read only property 'localStorage' of object '#<Window>'`
Error in Mozilla: `TypeError: setting getter-only property "localStorage"`

Followed this [doc](https://docs.colyseus.io/getting-started/javascript-client/#react-native-compatibility).
Error at line: `window.localStorage = AsyncStorage;`

**Comment by endel** [comment]
Hi @rhetoricalraj!

The workaround described in the docs is to use with React Native (iOS/Android)

React Native is not meant to run on browsers (Chrome, Mozilla) - so, this error is reasonable, as you can't override `window.localStorage` there.

I just realized assigning `window.localStorage` is only necessary if you'd like to use authentication (`client.auth`). If you're not going to use it, you can ignore this section of the workaround.

**Comment by rhetoricalraj** [comment]
Thanks for the quick reply!
It make sense.

**Comment by rhetoricalraj** [comment]
Update:
I was using expo to test in browser.
I found a work around.
If someone also stumbles upon this.

Rather than using
`window.localStorage = AsynStorage;`

Use this.
`Object.defineProperty(window, 'localStorage', { value: AsyncStorage, configurable: true, enumerable: true, writable: true });`

Hope this helps.
