### ISSUE TITLE
Not able to send Schema objects from client to server

### ISSUE THREAD

**Issue by dsarfati** [colyseus/colyseus.js#82]
I'm currently migrating my project from the `type: string | number, message?: any` style to simply sending Schema objects. This appears to be supported from the server to the client via the server's Room `send(message: Schema, options?: ISendOptions): void;` method.

It doesn't appear that there is an equivalent method to send a Schema class from the client to the server. The client side room only has a single send method. `send(type: string | number, message?: any): void;`

Is this something that could be implemented as a PR or should I be using the non-schema method for all my message passing?

**Comment by endel** [comment]
Hi @dsarfati, schema-encoded messages are only supported from server to client. You can pass regular objects on `room.send()` - messages are encoded using msgpack by default.

The schema-encoded messages from server to client were introduced to allow strongly typed messages for C#/Unity, but there are other ways of handling that in unity already - thus making me think of removing this feature to avoid confusion on a next version

**Comment by dsarfati** [comment]
Ok, thanks for the background. It sounds like I may not want to move all my messaging to Schema classes if that may go away in the future. From a developer experience, the Schema classes are very nice because I don't need to maintain the mappings on both sides.

**Comment by endel** [comment]
Closing as doesn't seem to be an issue
