### ISSUE TITLE
globalThis is not defined

### ISSUE THREAD

**Issue by TaoSiJun** [colyseus/colyseus.js#86]
i found your `WebSocketTransport.ts` where you used `globalThis`.

but, tsc not provides a support for `globalThis`.

it will throw `ReferenceError` in some low-device.

for example, android version  8.1.0, webview version 65.

please, check check.

thanks.

**Comment by endel** [comment]
Hi @TaoSiJun, thanks for reporting! I've published version `colyseus.js@0.14.12` with [this addition](https://github.com/colyseus/colyseus.js/commit/e61fd6f254d46a4ad388e6ca80ee2e58cfecb7d8), can you check if that works for you? 🙏

**Comment by TaoSiJun** [comment]
> Hi @TaoSiJun, thanks for reporting! I've published version `colyseus.js@0.14.12` with [this addition](https://github.com/colyseus/colyseus.js/commit/e61fd6f254d46a4ad388e6ca80ee2e58cfecb7d8), can you check if that works for you? 🙏

it works, thanks bro.
