### ISSUE TITLE
Make 'ws' a dependency not devDependency

### ISSUE THREAD

**Issue by middle-way-approach** [colyseus/colyseus.js#90]
Right not 'ws' is just a devDependency. This is not correct and leads to errors when used with e.g. Webpack 5 which will not install those.

**Comment by Wenish** [comment]
@middle-way-approach can you maybe explain when the error apears. do you talk about building colyseus.js or building your own project?

**Comment by middle-way-approach** [comment]
I am using the build of 'colyseus.js' in a Next.js application. This now uses Webpack 5 under the hood to bundle. The 'ws' module will not be installed, because it is not in the list of the dependencies, so I have to install it by hand.

**Comment by Wenish** [comment]
@middle-way-approach not sure what you are doing. but there is something wrong with the building of you project.
just a guess but maybe you reference colyseus.js from src folder. reference it from the dist folder.

**Comment by middle-way-approach** [comment]
I import it like 

`import { Room, Client } from "colyseus.js";`

So according to the `package.json` this points to `./build/esm/index.mjs`. In the file `./build/esm/transport/WebSocketTransport.mjs` there is an 

`import NodeWebSocket from 'ws';`

But the 'ws' package is not installed because it is listed as a dev dependency.
