### ISSUE TITLE
Secret State

### ISSUE THREAD

**Issue by dondragon2** [colyseus/colyseus.js#91]
How do we go about making pieces of the schema/state private only to a particular client? For example when developing a card game like blackjack or poker? The player should only see their hand and not that of the other players

**Comment by endel** [comment]
Hi @dondragon2, in a card game/turn-based scenario you can try out the @filter/@filterChildren: https://docs.colyseus.io/state/schema/#filtering-data-per-client

Beware this feature is experimental. The other way of handling private information would be to send messages directly to particular clients, using `client.send()` manually

**Comment by dondragon2** [comment]
But, isn't the entire state pushed to all clients automatically?

**Comment by endel** [comment]
@dondragon2 not when using filters! that's exactly what the experimental filter/filterChildren do - each client is going to receive its own filtered version of the state
