### ISSUE TITLE
Colyseus throws Server error when built in native

### ISSUE THREAD

**Issue by d3stryr** [colyseus/colyseus.js#92]
Hi, I recently came across colyseus and was able to build for web and it works fine
but when I build for native 
it creates a room but doesn't join 

it throws servererror

I am using javascript SDK in cocos creator 

can someone please help me out.

**Comment by d3stryr** [comment]
> What's the error? Can you provide a stack trace? What do you mean by Native? Are you using Cordova? React Native?
> 
> Don't expect we're gonna give attention to your issue if you don't give the necessary details to fix it.

I'm Sorry, I hit enter by mistake before detailing the issue

**Comment by endel** [comment]
What's the error message and/or stack trace? 

If you're running on the real device you'd need to provide the IP address as endpoint for connection rather than localhost.

**Comment by d3stryr** [comment]
I have hosted server in Heroku which is written in typescript and using that for web which works fine 
do I have to make changes for native or will the same code works?

the error just shows "ServerError" in catch function when joining the room

async connect () {
        try{
            this.node.getChildByName("data").getComponent(cc.Label).string="trying room ...."
            var room = await this.client.joinOrCreate('my_room')
            console.log(room);
            console.log("roomid : "+room.id);
            console.log("session Id  : "+room.sessionId);
            this.node.getChildByName("data").getComponent(cc.Label).string=" roomid : "+room.id+" session Id  : "+room.sessionId;
        }   
        catch(e)
        {
            this.node.getChildByName("data").getComponent(cc.Label).string=e;
            console.log(e.message);
        }
        
    }

**Comment by endel** [comment]
Closing old issues, feel free to re-add if you still have this issue, preferably with a reproduction scenario
