### ISSUE TITLE
"room.state.players.onAdd" is not triggered (run official examples locally)

### ISSUE THREAD

**Issue by tony709394** [colyseus/colyseus.js#93]
![](https://user-images.githubusercontent.com/30687593/130912714-cc754377-9714-4d4d-83a2-c244d331a87d.png)

![](https://user-images.githubusercontent.com/30687593/130912326-759baf72-c5ec-4889-96c1-1e4f6a9dcebd.png)

**Comment by endel** [comment]
Closing old issues, feel free to re-add if you still have this issue, preferably with a reproduction scenario
