### ISSUE TITLE
Cocos Creator Receive or Parse Schema

### ISSUE THREAD

**Issue by UFO-YZL** [colyseus/colyseus.js#95]
How to receive or parse the schema sent from the server to the client？
Can't the client use the Schema type?

**Comment by endel** [comment]
Sending or receiving schema messages is not recommended in JavaScript, see https://github.com/colyseus/colyseus.js/issues/82#issuecomment-757084281

PS: Do not use the issue tracker for questions, use discussions instead https://github.com/orgs/colyseus/discussions
