### ISSUE TITLE
Error : Cannot read properties of undefined (reading 'schema') 

### ISSUE THREAD

**Issue by aixasz** [colyseus/colyseus.js#98]
Hi there,

 I have found this issue when create a room and everything look good, but we have tried to create more room, and got this issue.  In the same case after room are destroyed (disposed) and got this issue when create room again. 
 
Following this image. 
![image](https://user-images.githubusercontent.com/2430853/140178567-f9935813-2e22-4d7d-81e3-494d6c4bb132.png)

### Call stack
```js
ChangeTree.prototype.getType = function (index) {
            if (this.ref['_definition']) {
                var definition = this.ref['_definition'];
                return definition.schema[definition.fieldsByIndex[index]];
            }
            else {
                var definition = this.parent['_definition'];
                var parentType = definition.schema[definition.fieldsByIndex[this.parentIndex]];
            ...
```

But room working correctly, and user can join and play a game until game is over (this only a room).

**Comment by endel** [comment]
Hi @aixasz, thanks for reporting. 

Could you possibly share a repository where we can reproduce this error? Does this happen on any clean NextJS app?

**Comment by lpsandaruwan** [comment]
Hi @endel 
I could not reproduce this behavior with NextJs. Sample is available [here](https://github.com/lpsandaruwan/colyseus-nextjs-example).

Hi @aixasz 
Thank you for reporting the bug. Can you please help with reproducing this? A working code repo/archive might be helpful.

**Comment by endel** [comment]
Need a reproduction scenario, feel free to reopen if you're still facing this issue
